# Generated by Django 4.2.6 on 2023-10-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('userid', models.CharField(default=None, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('email', models.CharField(default=None, max_length=30)),
                ('username', models.CharField(default=None, max_length=25)),
                ('password', models.CharField(default=None, max_length=16)),
                ('phone_num', models.CharField(default=None, max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='adminaccount',
            name='id',
        ),
        migrations.AddField(
            model_name='adminaccount',
            name='adminid',
            field=models.CharField(default=None, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
