# Generated by Django 4.2.6 on 2023-10-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clientaccount_remove_adminaccount_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(default=None, max_length=16, primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=20)),
                ('password', models.CharField(default=None, max_length=14)),
                ('access_type', models.IntegerField(default=3)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminAccount',
        ),
        migrations.DeleteModel(
            name='ClientAccount',
        ),
    ]
