# Generated by Django 4.2.6 on 2023-10-28 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_admin_delete_adminaccount_delete_clientaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default=None, max_length=16, primary_key=True, serialize=False)),
                ('email', models.CharField(default=None, max_length=25)),
                ('username', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(default=None, max_length=20)),
                ('phone_number', models.CharField(default=None, max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.CharField(default=None, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=35)),
                ('field', models.TextField(default=None)),
                ('date', models.DateField(default=None)),
                ('image', models.CharField(default=None, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionLists',
            fields=[
                ('id', models.CharField(default=None, max_length=16, primary_key=True, serialize=False)),
                ('_type', models.IntegerField(default=None)),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receipts')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.CharField(default=None, max_length=16, primary_key=True, serialize=False)),
                ('cost', models.PositiveIntegerField(default=None)),
                ('_type', models.ForeignKey(db_column='_type', on_delete=django.db.models.deletion.CASCADE, to='app.subscriptionlists')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(default=None, max_length=16, primary_key=True, serialize=False)),
                ('date', models.DateField(default=None)),
                ('_type', models.ForeignKey(db_column='_type', on_delete=django.db.models.deletion.CASCADE, to='app.subscriptiontier')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.CharField(default=None, max_length=16, primary_key=True, serialize=False)),
                ('expired_date', models.DateField(default=None)),
                ('_type', models.ForeignKey(db_column='_type', on_delete=django.db.models.deletion.CASCADE, to='app.subscriptiontier')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='subscription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subscriptions'),
        ),
    ]
