# Generated by Django 4.2.6 on 2023-11-02 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='subscriber_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptionlists',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='_type',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='_type',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='_type',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
