# Generated by Django 4.2.6 on 2023-11-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_client_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.CharField(default=None, max_length=16, primary_key=True, serialize=False),
        ),
    ]
