# Generated by Django 4.2.6 on 2023-11-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='image',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
