# Generated by Django 4.2.6 on 2023-11-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_receipts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlists',
            name='_type',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='_type',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='_type',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='_type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
